### ISSUE TITLE
Added to the idea2021.3.2

### ISSUE THREAD

**Issue by Jamie520** [moztl/Free-Mybatis-Tool#1]
java.lang.ClassCastException: class com.intellij.psi.search.searches.DefinitionsScopedSearch$SearchParameters cannot be cast to class com.intellij.psi.PsiElement (com.intellij.psi.search.searches.DefinitionsScopedSearch$SearchParameters and com.intellij.psi.PsiElement are in unnamed module of loader com.intellij.util.lang.PathClassLoader @543c6f6d)
	at com.tianlei.mybatis.definitionsearch.MapperDefinitionSearch.processQuery(MapperDefinitionSearch.java:12)
	at com.intellij.openapi.application.QueryExecutorBase.lambda$execute$1(QueryExecutorBase.java:62)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:69)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:28)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:108)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:37)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:83)
	at com.intellij.codeInsight.navigation.ImplementationSearcher$BackgroundableImplementationSearcher.searchDefinitions(ImplementationSearcher.java:123)
	at com.intellij.codeInsight.navigation.ImplementationSearcher.searchImplementations(ImplementationSearcher.java:36)
	at com.intellij.codeInsight.navigation.ImplementationSearcher.searchImplementations(ImplementationSearcher.java:28)
	at com.intellij.codeInsight.navigation.GotoImplementationHandler$ImplementationsUpdaterTask.run(GotoImplementationHandler.java:208)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by moztl** [comment]
To solve this problem, can you provide a list of plugins for idea.

**Comment by Jamie520** [comment]
Thanks for your prompt reply
This is my idea version information
and plugins info

IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2099.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 16
Non-Bundled Plugins:
    com.alibaba.p3c.smartfox (2.1.1)
    MavenRunHelper (4.20.213.3714.1)
    com.tianlei.plugin.mybatis (2.0.1)
    com.codota.csp.intellij (4.2.10)
    izhangzhihao.rainbow.brackets (6.21)
    cn.yiiguxing.plugin.translate (3.2.2-213)

Kotlin: 213-1.5.10-release-949-IJ6777.52

**Comment by moztl** [comment]
You can upgrade to the latest version(v2.0.2), hope it can solve your problem.
# Install the jar manually or Waiting for the approval of idea's marketplace.

**Comment by Jamie520** [comment]
Yes,I've upgraded, thank you very much.

**Comment by Jamie520** [comment]
Great feedback. Thumbs up for you.
