### ISSUE TITLE
多模块项目生成xml代码块异常

### ISSUE THREAD

**Issue by qq253498229** [moztl/Free-Mybatis-Tool#2]
我的环境是有多个模块，比如模块A和B，然后A和B里面都有同名的mapper和xml。
现在情况是在一个模块的mapper里面添加方法，生成xml代码块的时候会报错，错误如下，但生成之前还是能选择具体生成在哪个xml的，就是选完之后就报错：

```
com.intellij.util.IncorrectOperationException: Must not change PSI outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:270)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:579)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:673)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:53)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:447)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.addInternalSuper(XmlTagImpl.java:336)
	at com.intellij.psi.impl.source.xml.XmlTagImpl$XmlTagImplDelegate.addInternalSuper(XmlTagImpl.java:378)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.genericInsert(XmlTagDelegate.java:1081)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.addInternal(XmlTagDelegate.java:982)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.addInternal(XmlTagImpl.java:311)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.addAfter(CompositePsiElement.java:146)
	at com.intellij.util.xml.impl.DomInvocationHandler.addEmptyTag(DomInvocationHandler.java:780)
	at com.intellij.util.xml.impl.DomInvocationHandler.addCollectionChild(DomInvocationHandler.java:747)
	at com.intellij.util.xml.impl.AddChildInvocation.invoke(AddChildInvocation.java:43)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:658)
	at com.tianlei.mybatis.dom.model.Mapper$$EnhancerByJetBrainsMainCglib$$e98392cb.addSelect(<generated>)
	at com.tianlei.mybatis.generate.SelectGenerator.getTarget(SelectGenerator.java:21)
	at com.tianlei.mybatis.generate.StatementGenerator.setupTag(StatementGenerator.java:151)
	at com.tianlei.mybatis.generate.StatementGenerator$4.selected(StatementGenerator.java:139)
	at com.tianlei.mybatis.ui.UiComponentFacade$3.run(UiComponentFacade.java:113)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.tianlei.mybatis.ui.UiComponentFacade.setActionForExecutableListener(UiComponentFacade.java:97)
	at com.tianlei.mybatis.ui.UiComponentFacade$4.run(UiComponentFacade.java:119)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1508)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:186)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:175)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1505)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:217)
	at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:782)
	at com.intellij.ui.popup.AbstractPopup.closeOk(AbstractPopup.java:716)
	at com.intellij.openapi.ui.popup.PopupChooserBuilder.closePopup(PopupChooserBuilder.java:470)
	at com.intellij.openapi.ui.popup.PopupChooserBuilder$2.actionPerformed(PopupChooserBuilder.java:459)
	at java.desktop/javax.swing.JComponent$ActionStandin.actionPerformed(JComponent.java:3446)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2903)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2965)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2865)
	at java.desktop/java.awt.Component.processEvent(Component.java:6431)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:881)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1164)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4910)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:807)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by qq253498229** [comment]
又发现一个问题，也是同名的xml中，一个select节点的id是红色的，识别不到mapper；但是反过来都是正常的，从mapper可以跳转到xml，从service也能跳转到xml，就是xml往回识别不到

**Comment by moztl** [comment]
感谢您的反馈，核实完这个bug以后，将会在下一个版本v2.0.4修复。

**Comment by qq253498229** [comment]
还有点xml最上面的namespace，在同名xml之间也会跳转错误

**Comment by moztl** [comment]
[v2.0.4 ](https://github.com/moztl/Free-Mybatis-Tool/releases/tag/v2.0.4) 已发布最新版本，可以选择本地安装或者等待IDEA市场插件审核通过。
（Tips：同名包且同名类的情况下点击namespace跳转错误属于包读取错误并非插件引起，可点击左侧箭头功能正常返回[v2.0.4新增功能]，基于这个问题，会导致xml中方法变红，属于在错误包下未识别到相应方法，也可点击左侧箭头功能正常返回）

**Comment by qq253498229** [comment]
现在点击箭头可以整条在mapper/xml的方法之间跳转了，但是xml中的id还是报红

这是demo地址:

https://gitee.com/consolelog/spring-boot-oauth2-example.git

<img width="799" alt="image" src="https://user-images.githubusercontent.com/31200516/161202586-152b7d3d-d2cc-4762-977e-a125dd26d2b5.png">

**Comment by moztl** [comment]
目前是存在这个问题，上面的 Tips 里提到了，属于 namespace 归属错误导致引起方法识别错误与插件无关。v2.0.5我再出个解决方案。目前不影响正常使用
